// Personalised look for an edition of the archive: club colours, crest, nickname, stadium.
// Add an entry per edition number when it gets personalised. Editions without an entry use the normal look.
//
// colors: every key is optional; missing ones keep the site default.
//   rgb values ('255, 163, 0') are used for glows and soft backgrounds.
// crest: path in /public, or null → a round badge with the club's initials in `badge` colours.

export const EDITION_THEMES = {
  1: {
    club: 'Newport County',
    shortName: 'Newport',
    nickname: 'The Exiles',
    stadium: 'Rodney Parade',
    founded: 1912,
    colorsLabel: 'Amber & black',
    crest: '/crests/newport-county.png',
    badge: { bg: '#f2a900', fg: '#111111', ring: '#111111' },
    colors: {
      bg: '#0a0806',
      surface: '#15110b',
      surface2: '#1e1910',
      border: '#382d1c',
      text: '#f4efe6',
      muted: '#a99d89',
      accent: '#f2a900',
      accentInk: '#140c00',
      onAccent: '#140c00',
      accentRgb: '242, 169, 0',
      accentSoft: '#2b1f05',
      accentLine: '#6e500e',
      gold: '#ffd166',
      glowRgb: '255, 150, 0',
      headerRgb: '10, 8, 6',
      ogGlow: '#6b4200',
    },
  },
  2: {
    club: 'Notts County',
    shortName: 'Notts',
    nickname: 'The Magpies',
    stadium: 'Meadow Lane',
    founded: 1862,
    colorsLabel: 'Black & white',
    crest: '/crests/notts-county.png',
    badge: { bg: '#111111', fg: '#ffffff', ring: '#ffffff' },
    colors: {
      bg: '#080808',
      surface: '#121212',
      surface2: '#1b1b1b',
      border: '#2e2e2e',
      text: '#f4f4f4',
      muted: '#a0a0a0',
      accent: '#f4f4f4',
      accentInk: '#0a0a0a',
      onAccent: '#0a0a0a',
      accentRgb: '244, 244, 244',
      accentSoft: '#222222',
      accentLine: '#5a5a5a',
      gold: '#d9c48c',
      glowRgb: '150, 150, 150',
      headerRgb: '8, 8, 8',
      ogGlow: '#3a3a3a',
    },
  },
  3: {
    club: 'Cheltenham Town',
    shortName: 'Cheltenham',
    nickname: 'The Robins',
    stadium: 'Whaddon Road',
    founded: 1887,
    colorsLabel: 'Red & white',
    crest: '/crests/cheltenham-town.png',
    badge: { bg: '#d71f2a', fg: '#ffffff', ring: '#ffffff' },
    colors: {
      bg: '#0c0607',
      surface: '#170c0e',
      surface2: '#211215',
      border: '#3d2025',
      text: '#f7eeef',
      muted: '#b39a9d',
      accent: '#e5323b',
      accentInk: '#ffffff',
      onAccent: '#ffffff',
      accentRgb: '229, 50, 59',
      accentSoft: '#2e0e11',
      accentLine: '#7a2027',
      gold: '#ffd27a',
      glowRgb: '170, 25, 35',
      headerRgb: '12, 6, 7',
      ogGlow: '#6e1218',
    },
  },
  4: {
    club: 'Forest Green Rovers',
    shortName: 'Forest Green',
    nickname: 'Rovers (FGR)',
    stadium: 'The New Lawn',
    founded: 1889,
    colorsLabel: 'Green & black',
    crest: '/crests/forest-green-rovers.png',
    badge: { bg: '#7bc142', fg: '#0b1400', ring: '#111111' },
    colors: {
      bg: '#060a05',
      surface: '#0e150c',
      surface2: '#152012',
      border: '#26381f',
      text: '#eef6ea',
      muted: '#98aa90',
      accent: '#8fd14f',
      accentInk: '#0b1400',
      onAccent: '#0b1400',
      accentRgb: '143, 209, 79',
      accentSoft: '#18280f',
      accentLine: '#3f6a24',
      gold: '#e8d77a',
      glowRgb: '70, 140, 40',
      headerRgb: '6, 10, 5',
      ogGlow: '#24481a',
    },
  },
  5: {
    club: 'Oldham Athletic',
    shortName: 'Oldham',
    nickname: 'The Latics',
    stadium: 'Boundary Park',
    founded: 1895,
    colorsLabel: 'Blue & white',
    crest: '/crests/oldham-athletic.png',
    badge: { bg: '#1d4fb8', fg: '#ffffff', ring: '#ffffff' },
    colors: {
      bg: '#05080f',
      surface: '#0b1220',
      surface2: '#111a2e',
      border: '#202f4d',
      text: '#eef3fb',
      muted: '#93a2bf',
      accent: '#4d8ff5',
      accentInk: '#ffffff',
      onAccent: '#ffffff',
      accentRgb: '77, 143, 245',
      accentSoft: '#0d1d3d',
      accentLine: '#2a4f8f',
      gold: '#ffd36b',
      glowRgb: '30, 80, 200',
      headerRgb: '5, 8, 15',
      ogGlow: '#123a8a',
    },
  },
  6: {
    club: 'Salford City',
    shortName: 'Salford',
    nickname: 'The Ammies',
    stadium: 'Moor Lane',
    founded: 1940,
    colorsLabel: 'Red & white',
    crest: '/crests/salford-city.png',
    badge: { bg: '#ffffff', fg: '#d1121c', ring: '#d1121c' },
    colors: {
      bg: '#0b0506',
      surface: '#160b0c',
      surface2: '#201013',
      border: '#3b1c20',
      text: '#f8eeef',
      muted: '#b2999b',
      accent: '#ec2a34',
      accentInk: '#ffffff',
      onAccent: '#ffffff',
      accentRgb: '236, 42, 52',
      accentSoft: '#2f0c0f',
      accentLine: '#7d1c22',
      gold: '#f2f2f2',
      glowRgb: '150, 20, 28',
      headerRgb: '11, 5, 6',
      ogGlow: '#5e0e13',
    },
  },
  7: {
    club: 'Bolton Wanderers',
    shortName: 'Bolton',
    nickname: 'The Trotters',
    stadium: 'University of Bolton Stadium',
    founded: 1874,
    colorsLabel: 'White & navy',
    crest: '/crests/bolton-wanderers.png',
    badge: { bg: '#ffffff', fg: '#0a1a4f', ring: '#0a1a4f' },
    colors: {
      bg: '#05070f',
      surface: '#0b1020',
      surface2: '#11182e',
      border: '#222c4a',
      text: '#f3f5fa',
      muted: '#97a0ba',
      accent: '#f3f5fa',
      accentInk: '#0a1230',
      onAccent: '#0a1230',
      accentRgb: '243, 245, 250',
      accentSoft: '#18203a',
      accentLine: '#4a557a',
      gold: '#e8c35a',
      glowRgb: '40, 60, 140',
      headerRgb: '5, 7, 15',
      ogGlow: '#1b2a66',
    },
  },
  8: {
    club: 'Hartlepool United',
    shortName: 'Hartlepool',
    nickname: 'Pools',
    stadium: 'Victoria Park',
    founded: 1908,
    colorsLabel: 'Blue & white',
    crest: '/crests/hartlepool-united.png',
    badge: { bg: '#2a7dd1', fg: '#ffffff', ring: '#ffffff' },
    colors: {
      bg: '#050a10',
      surface: '#0b141f',
      surface2: '#111d2c',
      border: '#213449',
      text: '#eef4fa',
      muted: '#93a5ba',
      accent: '#3d97e6',
      accentInk: '#ffffff',
      onAccent: '#ffffff',
      accentRgb: '61, 151, 230',
      accentSoft: '#0d2236',
      accentLine: '#29567f',
      gold: '#ffd36b',
      glowRgb: '30, 110, 190',
      headerRgb: '5, 10, 16',
      ogGlow: '#134a7a',
    },
  },
  9: {
    club: '1860 Munich',
    shortName: '1860',
    nickname: 'Die Löwen (The Lions)',
    stadium: 'Grünwalder Stadion',
    founded: 1860,
    colorsLabel: 'Sky blue & white',
    crest: '/crests/1860-munich.png',
    colors: {
      bg: '#060a10',
      surface: '#0c141f',
      surface2: '#121d2c',
      border: '#223349',
      text: '#eef4fb',
      muted: '#93a6bd',
      accent: '#6cb8f0',
      accentInk: '#03111f',
      onAccent: '#03111f',
      accentRgb: '108, 184, 240',
      accentSoft: '#0e2236',
      accentLine: '#2b5577',
      gold: '#f2d27a',
      glowRgb: '40, 120, 190',
      headerRgb: '6, 10, 16',
      ogGlow: '#14507f',
    },
  },
  10: {
    club: 'Sutton United',
    shortName: 'Sutton',
    nickname: 'The U’s',
    stadium: 'Gander Green Lane',
    founded: 1898,
    colorsLabel: 'Amber & chocolate',
    crest: '/crests/sutton-united.png',
    colors: {
      bg: '#0c0805',
      surface: '#170f0a',
      surface2: '#21160e',
      border: '#3e2a1a',
      text: '#f6efe6',
      muted: '#ad9a86',
      accent: '#f6a81c',
      accentInk: '#1a0f00',
      onAccent: '#1a0f00',
      accentRgb: '246, 168, 28',
      accentSoft: '#2d1c08',
      accentLine: '#6f4714',
      gold: '#ffd27a',
      glowRgb: '120, 62, 22',
      headerRgb: '12, 8, 5',
      ogGlow: '#5a2f12',
    },
  },
  11: {
    club: 'Bromley',
    shortName: 'Bromley',
    nickname: 'The Ravens',
    stadium: 'Hayes Lane',
    founded: 1892,
    colorsLabel: 'White & black',
    crest: '/crests/bromley.png',
    colors: {
      bg: '#080808',
      surface: '#121212',
      surface2: '#1b1b1b',
      border: '#2e2e2e',
      text: '#f4f4f4',
      muted: '#a0a0a0',
      accent: '#f4f4f4',
      accentInk: '#0a0a0a',
      onAccent: '#0a0a0a',
      accentRgb: '244, 244, 244',
      accentSoft: '#222222',
      accentLine: '#5a5a5a',
      gold: '#c9a86a',
      glowRgb: '183, 150, 99',
      headerRgb: '8, 8, 8',
      ogGlow: '#4a3d27',
    },
  },
  12: {
    club: 'Cambridge United',
    shortName: 'Cambridge',
    nickname: 'The U’s',
    stadium: 'Abbey Stadium',
    founded: 1912,
    colorsLabel: 'Amber & black',
    crest: '/crests/cambridge-united.png',
    colors: {
      bg: '#0a0806',
      surface: '#15110b',
      surface2: '#1e1910',
      border: '#382d1c',
      text: '#f4efe6',
      muted: '#a99d89',
      accent: '#ffa000',
      accentInk: '#140c00',
      onAccent: '#140c00',
      accentRgb: '255, 160, 0',
      accentSoft: '#2b1d05',
      accentLine: '#6e4a0e',
      gold: '#ffd166',
      glowRgb: '255, 140, 0',
      headerRgb: '10, 8, 6',
      ogGlow: '#6b3d00', // background glow of the link-preview image (darker, so the crest stands out)
    },
  },
};

// Round initials badge as an SVG data link (used as tab icon and in link previews while there's no crest).
export function badgeDataUrl(theme, initials) {
  const b = theme?.badge || { bg: '#1840b8', fg: '#ffffff', ring: '#fdbe11' };
  const size = initials.length > 2 ? 30 : 38;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="46" fill="${b.bg}" stroke="${b.ring}" stroke-width="6"/><text x="50" y="50" dy="0.35em" text-anchor="middle" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="${size}" fill="${b.fg}">${initials}</text></svg>`;
  return `data:image/svg+xml;base64,${typeof btoa === 'function' ? btoa(svg) : Buffer.from(svg).toString('base64')}`;
}

export const editionTheme = (edition) => (edition ? EDITION_THEMES[edition.number] || null : null);

const VARS = {
  bg: '--bg', surface: '--surface', surface2: '--surface-2', border: '--border', text: '--text', muted: '--muted',
  accent: '--accent', accentInk: '--accent-ink', accentRgb: '--accent-rgb', accentSoft: '--accent-soft',
  accentLine: '--accent-line', onAccent: '--on-accent', gold: '--gold', glowRgb: '--glow-rgb', headerRgb: '--header-rgb',
};

// CSS that switches the whole page to the edition's colours (only while that edition is shown).
export function themeCss(theme) {
  if (!theme?.colors) return '';
  const decl = Object.entries(theme.colors)
    .filter(([k]) => VARS[k])
    .map(([k, v]) => `${VARS[k]}: ${v};`)
    .join(' ');
  return `:root { ${decl} }`;
}
